// certif-parent/certif-domain/src/main/java/com/certifapp/domain/model/user/User.java
package com.certifapp.domain.model.user;

import java.time.OffsetDateTime;
import java.util.UUID;

/**
 * Domain record representing a registered CertifApp user.
 *
 * <p>The {@code passwordHash} field contains a BCrypt hash (strength 12 minimum).
 * Plain-text passwords are never stored or passed through this record.</p>
 *
 * <p>Maps to the {@code users} table in PostgreSQL.</p>
 *
 * @param id               surrogate UUID generated by PostgreSQL
 * @param email            unique login identifier — lowercased on registration
 * @param passwordHash     BCrypt hash of the user's password
 * @param role             security role ({@link UserRole})
 * @param subscriptionTier current subscription level ({@link SubscriptionTier})
 * @param locale           BCP-47 language tag (e.g. {@code "fr"}, {@code "en"})
 * @param timezone         IANA timezone (e.g. {@code "Europe/Paris"})
 * @param stripeCustomerId Stripe customer ID — null for FREE users without payment method
 * @param isActive         false if the account has been suspended or deleted
 * @param createdAt        account creation timestamp
 * @param updatedAt        last profile modification timestamp
 */
public record User(
        UUID             id,
        String           email,
        String           passwordHash,
        UserRole         role,
        SubscriptionTier subscriptionTier,
        String           locale,
        String           timezone,
        String           stripeCustomerId,
        boolean          isActive,
        OffsetDateTime   createdAt,
        OffsetDateTime   updatedAt
) {
    /** Default locale for new users targeting the francophone market. */
    public static final String DEFAULT_LOCALE   = "fr";
    /** Default timezone for Metropolitan France. */
    public static final String DEFAULT_TIMEZONE = "Europe/Paris";

    /** Compact constructor — validates mandatory fields. */
    public User {
        if (email == null || email.isBlank())
            throw new IllegalArgumentException("email must not be blank");
        if (passwordHash == null || passwordHash.isBlank())
            throw new IllegalArgumentException("passwordHash must not be blank");
        if (role == null)
            throw new IllegalArgumentException("role must not be null");
        if (subscriptionTier == null)
            throw new IllegalArgumentException("subscriptionTier must not be null");
        email = email.toLowerCase().trim();
    }

    /**
     * Returns {@code true} if this user has access to premium AI features.
     *
     * @return {@code true} only for {@code PRO} subscribers
     */
    public boolean hasAiAccess() {
        return subscriptionTier.hasAiFeatures();
    }

    /**
     * Returns {@code true} if this user has unlimited exam access.
     *
     * @return {@code true} for {@code PRO} and {@code PACK}
     */
    public boolean hasUnlimitedAccess() {
        return subscriptionTier.isUnlimited();
    }
}
