// certif-domain/src/main/java/com/certifapp/domain/model/question/QuestionOption.java
package com.certifapp.domain.model.question;

import java.util.UUID;

/**
 * One answer choice within a {@link Question}.
 *
 * <p>Options are labelled A through E. The {@code isCorrect} flag identifies
 * the right answer(s). For {@code SINGLE_CHOICE} questions exactly one option
 * has {@code isCorrect = true}; for {@code MULTIPLE_CHOICE} one or more may.</p>
 *
 * <p>Maps to the {@code question_options} table in PostgreSQL.</p>
 *
 * @param id           surrogate UUID (generated by PostgreSQL)
 * @param questionId   parent question UUID
 * @param label        single uppercase letter: A, B, C, D or E
 * @param text         option text as displayed to the user
 * @param isCorrect    {@code true} if this option is a correct answer
 * @param displayOrder 0-based order matching the original JSON {@code options[]} array index
 */
public record QuestionOption(
        UUID    id,
        UUID    questionId,
        char    label,
        String  text,
        boolean isCorrect,
        int     displayOrder
) {

    /** Valid option labels. */
    private static final String VALID_LABELS = "ABCDE";

    /**
     * Compact constructor — validates label and display order.
     */
    public QuestionOption {
        if (VALID_LABELS.indexOf(Character.toUpperCase(label)) < 0) {
            throw new IllegalArgumentException(
                "Option label must be one of A-E, got: " + label);
        }
        if (displayOrder < 0 || displayOrder > 4) {
            throw new IllegalArgumentException(
                "displayOrder must be 0-4, got: " + displayOrder);
        }
        if (text == null || text.isBlank()) {
            throw new IllegalArgumentException("Option text must not be blank");
        }
        label = Character.toUpperCase(label);
    }

    /**
     * Creates an option from a JSON array entry (no UUID — before persistence).
     *
     * @param label        option letter (A/B/C/D)
     * @param text         option text
     * @param isCorrect    whether this option is the correct answer
     * @param displayOrder position in original options[] array
     * @return transient {@code QuestionOption} with {@code id = null} and {@code questionId = null}
     */
    public static QuestionOption of(char label, String text, boolean isCorrect, int displayOrder) {
        return new QuestionOption(null, null, label, text, isCorrect, displayOrder);
    }
}
