// certif-parent/certif-domain/src/main/java/com/certifapp/domain/model/learning/Course.java
package com.certifapp.domain.model.learning;

import java.time.OffsetDateTime;
import java.util.UUID;

/**
 * Preparatory course material for one theme of a certification.
 *
 * <p>One course per (certification, theme) pair. Content is generated by the AI pipeline
 * then reviewed by human admins before publication.
 * Maps to the {@code courses} table in PostgreSQL.</p>
 *
 * @param id              surrogate UUID
 * @param certificationId parent certification slug
 * @param themeId         parent theme UUID
 * @param title           display title
 * @param contentMarkdown editable Markdown source — authoritative content
 * @param contentHtml     pre-rendered HTML for performance
 * @param aiStatus        DRAFT | AI_GENERATED | HUMAN_REVIEWED | PUBLISHED
 * @param version         incremented on each significant revision
 * @param createdAt       creation timestamp
 * @param updatedAt       last modification timestamp
 */
public record Course(
        UUID id,
        String certificationId,
        UUID themeId,
        String title,
        String contentMarkdown,
        String contentHtml,
        String aiStatus,
        int version,
        OffsetDateTime createdAt,
        OffsetDateTime updatedAt
) {
    public Course {
        if (certificationId == null || certificationId.isBlank())
            throw new IllegalArgumentException("certificationId must not be blank");
        if (themeId == null)
            throw new IllegalArgumentException("themeId must not be null");
        if (title == null || title.isBlank())
            throw new IllegalArgumentException("title must not be blank");
        if (version < 1) version = 1;
    }

    /**
     * Returns {@code true} if this course is ready to be displayed to end-users.
     */
    public boolean isPublished() {
        return "PUBLISHED".equals(aiStatus);
    }
}
