// certif-parent/certif-domain/src/main/java/com/certifapp/domain/model/learning/Flashcard.java
package com.certifapp.domain.model.learning;

import java.time.OffsetDateTime;
import java.util.UUID;

/**
 * A two-sided study card (front = question, back = answer) for spaced-repetition review.
 *
 * <p>Flashcards are generated by the AI pipeline from Question corpus items
 * or from Course content. Maps to the {@code flashcards} table.</p>
 *
 * @param id          surrogate UUID
 * @param questionId  source question UUID — null if generated from a course
 * @param courseId    source course UUID   — null if generated from a question
 * @param frontText   concept / question on the front of the card
 * @param backText    answer / explanation on the back of the card
 * @param codeExample optional illustrative code snippet
 * @param aiGenerated {@code true} if generated by LangChain4j
 * @param createdAt   creation timestamp
 */
public record Flashcard(
        UUID id,
        UUID questionId,
        UUID courseId,
        String frontText,
        String backText,
        String codeExample,
        boolean aiGenerated,
        OffsetDateTime createdAt
) {
    public Flashcard {
        if (questionId == null && courseId == null)
            throw new IllegalArgumentException(
                    "A flashcard must have either a questionId or a courseId");
        if (frontText == null || frontText.isBlank())
            throw new IllegalArgumentException("frontText must not be blank");
        if (backText == null || backText.isBlank())
            throw new IllegalArgumentException("backText must not be blank");
    }

    /**
     * Creates a flashcard sourced from a corpus question.
     */
    public static Flashcard fromQuestion(UUID questionId, String front, String back,
                                         String code, boolean aiGenerated) {
        return new Flashcard(null, questionId, null, front, back, code,
                aiGenerated, OffsetDateTime.now());
    }

    /**
     * Creates a flashcard sourced from a course.
     */
    public static Flashcard fromCourse(UUID courseId, String front, String back,
                                       String code, boolean aiGenerated) {
        return new Flashcard(null, null, courseId, front, back, code,
                aiGenerated, OffsetDateTime.now());
    }
}
