# certif-parent/certif-web/sonar-project.properties
# Configuration SonarQube frontend Angular 18
# Projet : https://sonarcloud.io/project/overview?id=certifapp-frontend

sonar.projectKey=certifapp-frontend
sonar.projectName=CertifApp Frontend
sonar.projectVersion=1.0.0
sonar.organization=baloozeone972

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.exclusions=\
  **/node_modules/**,\
  **/dist/**,\
  **/coverage/**,\
  **/*.spec.ts,\
  **/environments/**,\
  **/assets/**

sonar.typescript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
