// certif-domain/src/main/java/com/certifapp/domain/model/certification/CertificationTheme.java
package com.certifapp.domain.model.certification;

import java.util.UUID;

/**
 * Represents a thematic category within a {@link Certification}.
 *
 * <p>Each certification is split into weighted themes (e.g. "Virtual Threads" = 60 questions
 * out of 500 for OCP21). Themes drive proportional question selection in FREE mode
 * and are the granularity level for theme-based scoring statistics.</p>
 *
 * <p>Immutable record — all fields are set at construction time.</p>
 *
 * @param id               surrogate UUID (generated by PostgreSQL)
 * @param certificationId  parent certification slug (e.g. {@code "ocp21"})
 * @param code             URL-safe slug derived from {@code label} (e.g. {@code "virtual_threads"})
 * @param label            display name imported from {@code config.json}
 *                         (e.g. {@code "Virtual Threads"})
 * @param questionCount    total questions available in this theme
 * @param weightPercent    official vendor weighting percentage — {@code null} if not published
 * @param displayOrder     0-based ordering index for UI presentation
 */
public record CertificationTheme(
        UUID   id,
        String certificationId,
        String code,
        String label,
        int    questionCount,
        Double weightPercent,
        int    displayOrder
) {

    /**
     * Compact constructor — validates invariants.
     *
     * @throws IllegalArgumentException if any required field is blank or counts are negative
     */
    public CertificationTheme {
        if (certificationId == null || certificationId.isBlank()) {
            throw new IllegalArgumentException("certificationId must not be blank");
        }
        if (code == null || code.isBlank()) {
            throw new IllegalArgumentException("code must not be blank");
        }
        if (label == null || label.isBlank()) {
            throw new IllegalArgumentException("label must not be blank");
        }
        if (questionCount < 0) {
            throw new IllegalArgumentException("questionCount must be >= 0, got: " + questionCount);
        }
        if (weightPercent != null && (weightPercent < 0 || weightPercent > 100)) {
            throw new IllegalArgumentException(
                "weightPercent must be between 0 and 100, got: " + weightPercent);
        }
    }

    /**
     * Creates a transient theme (before persistence — no UUID assigned yet).
     *
     * @param certificationId parent certification id
     * @param code            URL-safe slug
     * @param label           display name
     * @param questionCount   number of questions in this theme
     * @param displayOrder    ordering index
     * @return a new {@code CertificationTheme} with {@code id = null}
     */
    public static CertificationTheme of(
            String certificationId, String code, String label,
            int questionCount, int displayOrder) {
        return new CertificationTheme(
            null, certificationId, code, label, questionCount, null, displayOrder);
    }
}
