// certif-parent/certif-domain/src/main/java/com/certifapp/domain/model/coaching/UserCertPath.java
package com.certifapp.domain.model.coaching;

import java.time.OffsetDateTime;
import java.util.List;
import java.util.UUID;

/**
 * AI-generated personalised certification learning path for one user.
 *
 * <p>Generated by CertPathAdvisor (certif-ai) based on the user's role,
 * project goals and diagnostic results.
 * Maps to the {@code user_certification_paths} table in PostgreSQL.</p>
 *
 * @param id          surrogate UUID
 * @param userId      owner user UUID
 * @param roleType    declared professional role (e.g. "Java Developer")
 * @param projectGoal free-text goal description
 * @param steps       ordered list of certification steps
 * @param aiRationale AI explanation of this path ordering
 * @param createdAt   generation timestamp
 * @param updatedAt   last update timestamp
 */
public record UserCertPath(
        UUID id,
        UUID userId,
        String roleType,
        String projectGoal,
        List<PathStep> steps,
        String aiRationale,
        OffsetDateTime createdAt,
        OffsetDateTime updatedAt
) {
    public UserCertPath {
        if (userId == null) throw new IllegalArgumentException("userId must not be null");
        steps = steps == null ? List.of() : List.copyOf(steps);
    }

    /**
     * One ordered step in a certification learning path.
     *
     * @param certificationId certification to complete at this step
     * @param order           1-based position
     * @param rationale       AI justification for this position
     * @param estimatedWeeks  estimated preparation duration in weeks
     */
    public record PathStep(
            String certificationId,
            int order,
            String rationale,
            int estimatedWeeks
    ) {
        public PathStep {
            if (certificationId == null || certificationId.isBlank())
                throw new IllegalArgumentException("certificationId must not be blank");
            if (order < 1) throw new IllegalArgumentException("order must be >= 1");
            if (estimatedWeeks < 0)
                throw new IllegalArgumentException("estimatedWeeks must be >= 0");
        }
    }
}
